<?php
require_once('../../include/inc_load.php');
require_once(rel_admin_path.'/control_login.php');
require_once('general_tags.php');
require_once(rel_client_path.'/include/lib/Zebra_Mptt.php');
$mptt = new Zebra_Mptt();
 /* to transform a string in a json strin */
header("Cache-Control: no-cache, must-revalidate" );
header("Pragma: no-cache" );
header("Content-type: text/x-json");

//////////////////////////////////////////////////////////////
////////////////////    SET VARIABLES    ////////////////////
/////////////////////////////////////////////////////////////
$table = $table_name; /* request of table where script reads data */
$counter = 0; /* start counter */
if(isset($_POST['rp'])){
  $counter = $_POST['rp']; /* request of item per page (it's generated by flexigred plugin */
}

//////////////////////////////////////////////////////////////
//////////////////// SEARCH VARIABLES   //////////////////////
/////////////////////////////////////////////////////////////
$sqlsearch = ''; /* it's important for advanced search */
$sqlsearch_or = ''; /* it contains condition with or clausole in query (in this case it's not important to set)*/

/*
 these conditions are important for advanced seach
 if you want add other condition take in mind the name of the fields of the search form
 and follow the examples
*/

if (isset($_POST['name_r']) && $_POST['name_r']){
 $sqlsearch .= " (name Like '%".str_db($_POST['name_r'])."%' or code Like '%".str_db($_POST['name_r'])."%') and ";
}
if (isset($_POST['offer_r']) && $_POST['offer_r']){
 $sqlsearch .= " (offer > 0) and ";
}

$sqlsearch .= '(';
if ((isset($_POST['visible_r']) && $_POST['visible_r']) || !isset($_POST['notvisible_r'])){
 $sqlsearch .= " active = 1 or ";
}
if (!isset($_POST['visible_r']) || (isset($_POST['notvisible_r']) && $_POST['notvisible_r'])){
 $sqlsearch .= " active = 0 or ";
}
$sqlsearch = mb_substr($sqlsearch, 0, mb_strlen($sqlsearch) - 4).') and (';
if ((isset($_POST['showcase_r']) && $_POST['showcase_r']) || !isset($_POST['notshowcase_r'])){
 $sqlsearch .= " showcase = 1 or ";
}
if (!isset($_POST['showcase_r']) || (isset($_POST['notshowcase_r']) && $_POST['notshowcase_r'])){
 $sqlsearch .= " showcase = 0 or ";
}
if(plugin_exsists('dgoods')){
  $sqlsearch = mb_substr($sqlsearch, 0, mb_strlen($sqlsearch) - 4).') and (';
  if ((isset($_POST['digital_good_r']) && $_POST['digital_good_r']) || !isset($_POST['not_digital_good_r'])){
   $sqlsearch .= " pl_digital = 1 or ";
  }
  if (!isset($_POST['digital_good_r']) || (isset($_POST['not_digital_good_r']) && $_POST['not_digital_good_r'])){
   $sqlsearch .= " pl_digital = 0 or ";
  }
}
$sqlsearch = mb_substr($sqlsearch, 0, mb_strlen($sqlsearch) - 4).') and ';

if (isset($_POST['category_r']) && $_POST['category_r']){
 $sqlsearch_or .= " (categories = '".str_db($_POST['category_r'])."') or ";
}
if (isset($_POST['uncategorized_r']) && $_POST['uncategorized_r']){
 $sqlsearch_or .= " (categories = 0) or ";
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////

$order_record = 'id'; /* record to sort data (if it's not specified in js code in files_upload.php) */
$order_verse = 'desc'; /* sort order (if it's not specified in js code in files_upload.php) */

/* some conditions for pagination (non change them) */
if (isset($_POST['sortname']) && $_POST['sortname'] != 'undefined'){
 $order_record = $_POST['sortname'];
}
if (isset($_POST['sortorder']) && $_POST['sortorder'] != 'undefined'){
 $order_verse = $_POST['sortorder'];
}
$pag = 1;
if (isset($_POST['page'])){
 $pag = $_POST['page'];
}
if (is_numeric($pag) == 0 || $pag < '1'){
 $pag = 1;
}
$limit_end = $counter;
$limit_start = ($pag - 1) * $limit_end;

if ($sqlsearch_or != ''){
  $sqlsearch = $sqlsearch . '('.$sqlsearch_or;
}

 if ($sqlsearch != ''){
   if ($sqlsearch_or != ''){
    $sqlsearch = ' Where ' . mb_substr($sqlsearch, 0, mb_strlen($sqlsearch) - 4).')';
   }else{
    $sqlsearch = ' Where ' . mb_substr($sqlsearch, 0, mb_strlen($sqlsearch) - 5);
   }
 }
  $sql = ' select * from '.$table.' ' . $sqlsearch;


  $rs_result = execute($sql);
  $initial_array = array();

while ($rs = mysql_fetch_array($rs_result)) {

   $tree = explode(',',$rs['categories']);
   $tree_path = '';
   foreach($tree as $category){
	   $tree_path .= '<span style="margin-right:3px;margin-bottom:3px;" class="label label-success">'.$mptt -> get_orizzontal($category,' > ').'</span>';
   }
   $img_del = '<span class="btn btn-danger action-delete" id="'.$rs['id'].'" style="cursor:pointer;margin-right:5px;" rel-tooltip="tooltip" title="'.$lang_['table']['FLEX_ACTION_DELETE'].'"><i class="icon-trash icon-white"></i> </span>';
   $img_edit = '<span class="btn btn-success action-edit" id="'.$rs['id'].'" style="cursor:pointer;margin-right:10px;" rel-tooltip="tooltip" title="'.$lang_['table']['FLEX_ACTION_EDIT'].'"><i class="icon-edit icon-white"></i> </span>';
   $img_info = '<span class="btn btn-info action-info" id="'.$rs['id'].'" style="cursor:pointer;margin-right:10px;" rel-tooltip="tooltip" title="'.$lang_['table']['FLEX_ACTION_INFO'].'"><i class="icon-info-sign icon-white"></i> </span>';
   $img_prew = '<a class="btn" href="'.path_abs_products.'/'.$rs['id'].'-'.($rs['file_name'] != '' ? $rs['file_name'] : filesystem($rs['name'])).'.php" target="_blank" style="cursor:pointer;margin-right:10px;" rel-tooltip="tooltip" title="'.$lang_['table']['FLEX_ACTION_PREVIEW'].'"><i class="icon-search"></i></a>';
   $img_enabled = '<span class="btn action-enable'.($rs['active'] ? ' processed btn-success' : ' btn-warning').'" id="'.$rs['id'].'" style="cursor:pointer;margin-right:10px;" rel-tooltip="tooltip" title="'.($rs['active'] ? $lang_['products']['TOOLTIP_DISABLED'] : $lang_['products']['TOOLTIP_ENABLED']).'"><i class="icon-white icon-eye-'.($rs['active'] ? 'open' : 'close').'"></i></span>';
   $img_showcase = '<span class="btn action-showcase'.($rs['showcase'] ? ' processed btn-success' : ' btn').'" id="'.$rs['id'].'" style="cursor:pointer;margin-right:10px;" rel-tooltip="tooltip" title="'.($rs['showcase'] ? $lang_['products']['TOOLTIP_NOT_SHOWCASE'] : $lang_['products']['TOOLTIP_SHOWCASE']).'"><i class="'.($rs['showcase'] ? 'icon-white icon-thumbs-up' : 'icon-ban-circle').'"></i></span>';
   $slect_checkbox = '<input type="checkbox" id="'.$rs['id'].'" value="'.$rs['id'].'" name="box_delete[]" class="check_selezione" align="absmiddle" />';
   $img_product = $rs['url_image'] != '' ? path_abs_img_products.'/'.$rs['id'].'/300x300/1_'.$rs['url_image'] : path_img_back.'/img_not_available.jpg';
	/* here start the part that provides to return data ----- from here to... (NOT CHANGE/DELETE ID ADN SELECT_CHECKBOX KEY, NOT DELETE ACTIONS KEY-YOU CAN EDIT IT ONLY)*/
	  $initial_array[] = array(
	   "id" => $rs['id'],
	   "price" => str_json($currency.' '.num_formatt($rs['price'])),
	   "offer" => ($rs['offer'] > 0 ? str_json($currency.' '.num_formatt($rs['offer'])) : ''),
	   "rprice" => plugin_exsists('businesstype') && get_admin_business_bc() ? str_json('<br/>b2b: '.$currency.' '.num_formatt($rs['rprice'])) : '',
	   "roffer" => plugin_exsists('businesstype') && get_admin_business_bc() ? ($rs['roffer'] > 0 ? str_json('<br/>b2b: '.$currency.' '.num_formatt($rs['roffer'])) : '') : '',
	   "name" => str_json($rs['name']),
	   "code" => str_json($rs['code']),
	   "availability" => ($rs['unlimited_availability'] ? 'unlimited' : str_json(num_formatt($rs['availability'],2,true))),
	   "url_image" => str_json('<img src="'.$img_product.'" alt="" />'),
	   "categories" => str_json($tree_path),
	   "slect_checkbox" => str_json($slect_checkbox),
	   "actions" => str_json($img_prew.$img_enabled.$img_showcase.$img_edit.$img_info.$img_del)
	  );
}
	$result  = '{';
	$result .= '"page":'.$pag.',';
	$result .= '"total":'.count($initial_array).'';
	if(!empty($initial_array)){
		$result .= ",\"rows\":[";
		$initial_array = array_msort($initial_array, array($order_record=>mb_strtolower($order_verse) == 'asc' ? SORT_ASC : SORT_DESC));
		$initial_array = array_slice($initial_array,$limit_start,$limit_end);
		foreach($initial_array as $item){
		   $result .= '{';
		   $result .= '"id":"'.$item['id'].'",';
		   $result .= '"cell":{';
		   $result .= '"id":"'.$item['id'].'",';
		   $result .= '"check":"'.$item['slect_checkbox'].'",';
		/* ... here no change

		if you want add other data please follow the code below:
		   e.g. if a record named xxx is in table and you want add its to date you do this:
		   $result .= '"xxx":"'.str_json($rs['xxx']).'",';
		   after in "index.php" file in this directory integrate js code in this way :
		   {display: 'XXX', name : 'xxx', width : 180, sortable : true, align: 'left'},
		*/
		   $result .= '"url_image":"'.$item['url_image'].'",';
		   $result .= '"name":"'.$item['name'].'",';
		   $result .= '"price":"'.$item['price'].$item['rprice'].'",';
		   $result .= '"offer":"'.$item['offer'].$item['roffer'].'",';
		   $result .= '"code":"'.$item['code'].'",';
		   $result .= '"categories":"'.$item['categories'].'",';
		   $result .= '"availability":"'.$item['availability'].'",';
		   $result .= '"actions":"'.$item['actions'].'"';
		/* from here to the end no change */
		   $result .= '}},';
		}
		$result = mb_substr($result,0,mb_strlen($result)-1);
		$result .= "]";
	}
$result .= "}";
echo $result;
?>