<?php
require_once('../../include/inc_load.php');
require_once(rel_admin_path.'/control_login.php');
require_once('general_tags.php');
 /* to transform a string in a json strin */
header("Cache-Control: no-cache, must-revalidate" );
header("Pragma: no-cache" );
header("Content-type: text/x-json");

//////////////////////////////////////////////////////////////
////////////////////    SET VARIABLES    ////////////////////
/////////////////////////////////////////////////////////////
$table = $table_name; /* request of table where script reads data */
$counter = 0; /* start counter */
if(isset($_POST['rp'])){
  $counter = $_POST['rp']; /* request of item per page (it's generated by flexigred plugin */
}

//////////////////////////////////////////////////////////////
//////////////////// SEARCH VARIABLES   //////////////////////
/////////////////////////////////////////////////////////////
$sqlsearch = ''; /* it's important for advanced search */
$sqlsearch_or = ''; /* it contains condition with or clausole in query (in this case it's not important to set)*/

/* 
 these conditions are important for advanced seach
 if you want add other condition take in mind the name of the fields of the search form
 and follow the examples
*/

if (isset($_POST['code_r']) && $_POST['code_r']){
 $sqlsearch .= " (code_order = '".str_db($_POST['code_r'])."') and ";
}
if (isset($_POST['client_r']) && $_POST['client_r']){
 $sqlsearch .= " (id_client = '".$_POST['client_r']."') and ";
}

if ($_POST['datefrom_r'] != '' && $_POST['dateto_r'] != '' && (is_valid_date($_POST['datefrom_r']) && is_valid_date($_POST['dateto_r']))){
 $sqlsearch.= " (data <> '00-00-0000 00:00:00' and data >= '".date("Y-m-d 00:00:00",strtotime(conv_date_db($_POST['datefrom_r'])))."' and data <= '".date("Y-m-d 23:59:59",strtotime(conv_date_db($_POST['dateto_r'])))."') and ";
}
if ($_POST['datefrom_r'] != '' && $_POST['dateto_r'] == '' && (is_valid_date($_POST['datefrom_r']) && is_valid_date($_POST['dateto_r']))){
 $sqlsearch.= " (data <> '00-00-0000 00:00:00' and data >= '".date("Y-m-d 00:00:00",strtotime(conv_date_db($_POST['datefrom_r'])))."') and ";
}
if ($_POST['datefrom_r'] == '' && $_POST['dateto_r'] != '' && is_valid_date($_POST['dateto_r'])){
 $sqlsearch.= " (data <> '00-00-0000 00:00:00' and data <= '".date("Y-m-d 23:59:59",strtotime(conv_date_db($_POST['dateto_r'])))."') and ";
}

if ($_POST['processingdatefrom_r'] != '' && $_POST['processingdateto_r'] != '' && (is_valid_date($_POST['processingdatefrom_r']) && is_valid_date($_POST['processingdateto_r']))){
 $sqlsearch.= " (process_date <> '00-00-0000 00:00:00' and process_date >= '".date("Y-m-d 00:00:00",strtotime(conv_date_db($_POST['processingdatefrom_r'])))."' and process_date <= '".date("Y-m-d 23:59:59",strtotime(conv_date_db($_POST['processingdateto_r'])))."') and ";
}
if ($_POST['processingdatefrom_r'] != '' && $_POST['processingdateto_r'] == '' && (is_valid_date($_POST['processingdatefrom_r']) && is_valid_date($_POST['processingdateto_r']))){
 $sqlsearch.= " (process_date <> '00-00-0000 00:00:00' and process_date >= '".date("Y-m-d 00:00:00",strtotime(conv_date_db($_POST['processingdatefrom_r'])))."') and ";
}
if ($_POST['processingdatefrom_r'] == '' && $_POST['processingdateto_r'] != '' && is_valid_date($_POST['processingdateto_r'])){
 $sqlsearch.= " (process_date <> '00-00-0000 00:00:00' and process_date <= '".date("Y-m-d 23:59:59",strtotime(conv_date_db($_POST['processingdateto_r'])))."') and ";
}
$sqlsearch .= '(';
if ((isset($_POST['processed_r']) && $_POST['processed_r']) || !isset($_POST['notprocessed_r'])){
 $sqlsearch .= " processed = 1 or ";
}
if (!isset($_POST['processed_r']) || (isset($_POST['notprocessed_r']) && $_POST['notprocessed_r'])){
 $sqlsearch .= " processed = 0 or ";
}
$sqlsearch = mb_substr($sqlsearch, 0, mb_strlen($sqlsearch) - 4).') and (';
if ((isset($_POST['payed_r']) && $_POST['payed_r']) || !isset($_POST['notpayed_r'])){
 $sqlsearch .= " payed = 1 or ";
}
if (!isset($_POST['payed_r']) || (isset($_POST['notpayed_r']) && $_POST['notpayed_r'])){
 $sqlsearch .= " payed = 0 or ";
}
$sqlsearch = mb_substr($sqlsearch, 0, mb_strlen($sqlsearch) - 4).') and (';
if ((isset($_POST['guest_r']) && $_POST['guest_r']) || !isset($_POST['notguest_r'])){
 $sqlsearch .= " guest = 1 or ";
}
if (!isset($_POST['guest_r']) || (isset($_POST['notguest_r']) && $_POST['notguest_r'])){
 $sqlsearch .= " guest = 0 or ";
}
$sqlsearch = mb_substr($sqlsearch, 0, mb_strlen($sqlsearch) - 4).') and ';
/////////////////////////////////////////////////////////////////////////////////////////////////////////////

$order_record = 'id'; /* record to sort data (if it's not specified in js code in files_upload.php) */
$order_verse = 'desc'; /* sort order (if it's not specified in js code in files_upload.php) */

/* some conditions for pagination (non change them) */
if (isset($_POST['sortname']) && $_POST['sortname'] != 'undefined'){ 
 $order_record = $_POST['sortname'];
}
if (isset($_POST['sortorder']) && $_POST['sortorder'] != 'undefined'){ 
 $order_verse = $_POST['sortorder'];
}
$pag = 1;
if (isset($_POST['page'])){ 
 $pag = $_POST['page'];
}
if (is_numeric($pag) == 0 || $pag < '1'){ 
 $pag = 1;
}
$limit_end = $counter;
$limit_start = ($pag - 1) * $limit_end;

if ($sqlsearch_or != ''){
  $sqlsearch = $sqlsearch . '('.$sqlsearch_or; 
}

 if ($sqlsearch != ''){ 
   if ($sqlsearch_or != ''){
    $sqlsearch = ' Where ' . mb_substr($sqlsearch, 0, mb_strlen($sqlsearch) - 4).')';
   }else{
    $sqlsearch = ' Where ' . mb_substr($sqlsearch, 0, mb_strlen($sqlsearch) - 5);
   }
 }
  $sql = ' select * from '.$table.' ' . $sqlsearch;

  
  
  $rs_result = execute($sql);   
  $initial_array = array();
  
while ($rs = mysql_fetch_array($rs_result)) {
	   	
   $img_del = '<span class="btn btn-danger action-delete" id="'.$rs['id'].'" style="cursor:pointer;margin-right:5px;" rel-tooltip="tooltip" title="'.$lang_['table']['FLEX_ACTION_DELETE'].'"><i class="icon-trash icon-white"></i> </span>';
   $img_edit = '<span class="btn btn-success action-edit" id="'.$rs['id'].'" style="cursor:pointer;margin-right:10px;" rel-tooltip="tooltip" title="'.$lang_['table']['FLEX_ACTION_EDIT'].'"><i class="icon-edit icon-white"></i> </span>';
   $img_info = '<span class="btn btn-info action-info" id="'.$rs['id'].'" style="cursor:pointer;margin-right:10px;" rel-tooltip="tooltip" title="'.$lang_['table']['FLEX_ACTION_INFO'].'"><i class="icon-info-sign icon-white"></i> </span>';
   $img_carrier = '<span class="btn action-process'.($rs['processed'] ? ' processed btn-success' : ' btn-warning').'" id="'.$rs['id'].'" style="cursor:pointer;margin-right:10px;" rel-tooltip="tooltip" title="'.($rs['processed'] ? $lang_['orders']['TOOLTIP_MARK_NOT_PROCESSED'] : $lang_['orders']['TOOLTIP_MARK_PROCESSED']).'"><img src="carrier_icon.png" /> </span>';   
   $img_payment = '<span class="btn action-pay'.($rs['payed'] ? ' processed btn-success' : ' btn-warning').($rs['payment_method'] == 'PAYPAL' && $rs['paypal_id_transaction'] != '' ? ' disabled' : '').'" id="'.$rs['id'].'" style="cursor:pointer;margin-right:10px;" rel-tooltip="tooltip" title="'.($rs['payed'] ? $lang_['orders']['TOOLTIP_MARK_NOT_PAYED'] : $lang_['orders']['TOOLTIP_MARK_PAYED']).'"><img src="payed_icon.png" /> </span>';
   $processed_status = $rs['processed'] ? 'icon-check' : 'icon-close';
   $payment_status = $rs['payed'] ? 'icon-check' : 'icon-close';
   $slect_checkbox = '<input type="checkbox" id="'.$rs['id'].'" value="'.$rs['id'].'" name="box_delete[]" class="check_selezione" align="absmiddle" />';
	/* here start the part that provides to return data ----- from here to... (NOT CHANGE/DELETE ID ADN SELECT_CHECKBOX KEY, NOT DELETE ACTIONS KEY-YOU CAN EDIT IT ONLY)*/  
	  $initial_array[] = array(
	   "id" => $rs['id'],
	   "data" => str_json('<span style="display:none">'.$rs['data'].'</span>'.view_date($rs['data']).' '.date("H:i:s",strtotime($rs['data']))),
	   "process_date" => $rs['process_date'] != '0000-00-00 00:00:00' ? str_json('<span style="display:none">'.$rs['process_date'].'</span>'.view_date($rs['process_date']).' '.date("H:i:s",strtotime($rs['process_date']))) : '',
	   "code_order" => str_json($rs['code_order']),
	   "grandtotal" => str_json(num_formatt($rs['grandtotal'])),
	   "processed_status" => str_json('<span style="display:none">'.$rs['processed'].'</span><i class="icon icon-color '.$processed_status.'"></i>'),
	   "payment_status" => str_json('<span style="display:none">'.$rs['payed'].'</span><i class="icon icon-color '.$payment_status.'"></i>'),
	   "slect_checkbox" => str_json($slect_checkbox),
	   "actions" => str_json($img_payment.$img_carrier.$img_info.$img_del)
	  );   
}
	$result  = '{';
	$result .= '"page":'.$pag.',';
	$result .= '"total":'.count($initial_array).'';	
	if(!empty($initial_array)){
		$result .= ",\"rows\":[";
		$initial_array = array_msort($initial_array, array($order_record=>mb_strtolower($order_verse) == 'asc' ? SORT_ASC : SORT_DESC));	
		$initial_array = array_slice($initial_array,$limit_start,$limit_end);
		foreach($initial_array as $item){
		   $result .= '{';
		   $result .= '"id":"'.$item['id'].'",';
		   $result .= '"cell":{';
		   $result .= '"id":"'.$item['id'].'",';
		   $result .= '"check":"'.$item['slect_checkbox'].'",';
		/* ... here no change 
			  
		if you want add other data please follow the code below:
		   e.g. if a record named xxx is in table and you want add its to date you do this:
		   $result .= '"xxx":"'.str_json($rs['xxx']).'",';
		   after in "index.php" file in this directory integrate js code in this way :
		   {display: 'XXX', name : 'xxx', width : 180, sortable : true, align: 'left'},
		*/
		   $result .= '"data":"'.$item['data'].'",';
		   $result .= '"process_date":"'.$item['process_date'].'",';
		   $result .= '"code_order":"'.$item['code_order'].'",';
		   $result .= '"grandtotal":"'.$item['grandtotal'].'",';
		   $result .= '"processed_status":"'.$item['processed_status'].'",';
		   $result .= '"payment_status":"'.$item['payment_status'].'",';
		   $result .= '"actions":"'.$item['actions'].'"';
		/* from here to the end no change */   
		   $result .= '}},';   
		}
		$result = mb_substr($result,0,mb_strlen($result)-1); 
		$result .= "]";		
	} 
$result .= "}"; 
echo $result;
?>